name: ovision
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.3.1"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  video_player: ^2.4.7
  firebase_core:
  firebase_storage: ^11.2.1
  firebase_auth: ^4.6.1
  file_picker: ^5.2.0+1
  cloud_firestore: ^4.7.1
  permission_handler: ^10.1.0
  
  firebase_core_platform_interface: ^4.8.0
  firebase_messaging: ^14.6.1
  firebase: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
      - images/as.jpeg
      - images/as.png
      - images/logo_github.png
  